version: '3.8'

services:
  nlp-app:
    build: .
    container_name: persian-nlp-container
    ports:
      - "5001:5000"  # HOST:CONTAINER – opens your app at http://localhost:5001
    volumes:
      - .:/app
    restart: unless-stopped
